name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: Describe the feature
      placeholder: What problem does it solve?
    validations:
      required: true
