name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

        **💡 Tip**: Use Claude Code to design the feature:
        ```
        @claude Design a solution for: [your feature request]
        Consider: [constraints, requirements]
        ```
        See [AI-AGENT-WORKFLOWS.md](../../docs/AI-AGENT-WORKFLOWS.md) for design patterns.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm frustrated when... / Users need a way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like the system to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I also thought about...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you (or users) would use this feature
      placeholder: |
        As a [user type],
        I want to [action],
        So that [benefit].

        Example workflow:
        1. User navigates to...
        2. User clicks...
        3. System displays...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What needs to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Users can...
        - [ ] System validates...
        - [ ] Error handling for...
        - [ ] Documentation updated...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocks work)
        - High (significantly improves workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: User Impact
      description: How many users would benefit from this?
      options:
        - All users
        - Most users
        - Some users
        - Few users (specific use case)
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If applicable, add mockups, wireframes, or examples from other systems
      placeholder: Drag and drop images or paste links here

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical constraints or considerations?
      placeholder: |
        - May require database migration
        - Should integrate with existing auth system
        - Performance implications for large datasets

  - type: textarea
    id: ai-design
    attributes:
      label: AI Design Suggestions (Optional but Recommended)
      description: If you used Claude Code to design this feature, paste the suggestions here
      placeholder: |
        @claude design suggestions:

        **Architecture:**
        - ...

        **Implementation approach:**
        - ...

        **Considerations:**
        - ...
      render: markdown

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, references, or information
      placeholder: Similar feature exists in [other product]...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear use case for this feature
          required: true
        - label: I am willing to contribute to implementing this feature
          required: false
